// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package itemdb

import (
	"context"
	"time"
)

const create = `-- name: Create :one
INSERT INTO
  item (name, description, images, price, condition, is_negotiable, category, subcategory, placeholder, seller)
VALUES
  ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, name, description, images, price, condition, is_negotiable, posted_at, sold_at, views, category, subcategory, fts, placeholder, likes, seller
`

type CreateParams struct {
	Name         string   `json:"name"`
	Description  string   `json:"description"`
	Images       []string `json:"images"`
	Price        float64  `json:"price"`
	Condition    int16    `json:"condition"`
	IsNegotiable bool     `json:"is_negotiable"`
	Category     string   `json:"category"`
	Subcategory  string   `json:"subcategory"`
	Placeholder  string   `json:"placeholder"`
	Seller       string   `json:"seller"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (Item, error) {
	row := q.db.QueryRow(ctx, create,
		arg.Name,
		arg.Description,
		arg.Images,
		arg.Price,
		arg.Condition,
		arg.IsNegotiable,
		arg.Category,
		arg.Subcategory,
		arg.Placeholder,
		arg.Seller,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Images,
		&i.Price,
		&i.Condition,
		&i.IsNegotiable,
		&i.PostedAt,
		&i.SoldAt,
		&i.Views,
		&i.Category,
		&i.Subcategory,
		&i.Fts,
		&i.Placeholder,
		&i.Likes,
		&i.Seller,
	)
	return i, err
}

const decrementLike = `-- name: DecrementLike :exec
UPDATE
  item
SET
  likes = GREATEST(likes - 1, 0)
WHERE
  id = $1
`

func (q *Queries) DecrementLike(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, decrementLike, id)
	return err
}

const delete = `-- name: Delete :exec
DELETE FROM
  item
WHERE
  id = $1
`

func (q *Queries) Delete(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, delete, id)
	return err
}

const get = `-- name: Get :one
SELECT
  id, name, description, images, price, condition, is_negotiable, posted_at, sold_at, views, category, subcategory, fts, placeholder, likes, seller
FROM
  item
WHERE
  id = $1
`

func (q *Queries) Get(ctx context.Context, id int64) (Item, error) {
	row := q.db.QueryRow(ctx, get, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Images,
		&i.Price,
		&i.Condition,
		&i.IsNegotiable,
		&i.PostedAt,
		&i.SoldAt,
		&i.Views,
		&i.Category,
		&i.Subcategory,
		&i.Fts,
		&i.Placeholder,
		&i.Likes,
		&i.Seller,
	)
	return i, err
}

const getAll = `-- name: GetAll :many
SELECT
  id, name, description, images, price, condition, is_negotiable, posted_at, sold_at, views, category, subcategory, fts, placeholder, likes, seller
FROM
  item
`

func (q *Queries) GetAll(ctx context.Context) ([]Item, error) {
	rows, err := q.db.Query(ctx, getAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Images,
			&i.Price,
			&i.Condition,
			&i.IsNegotiable,
			&i.PostedAt,
			&i.SoldAt,
			&i.Views,
			&i.Category,
			&i.Subcategory,
			&i.Fts,
			&i.Placeholder,
			&i.Likes,
			&i.Seller,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByCategory = `-- name: GetByCategory :many
SELECT
  id, name, description, images, price, condition, is_negotiable, posted_at, sold_at, views, category, subcategory, fts, placeholder, likes, seller
FROM
  item
WHERE
  category = $1
`

func (q *Queries) GetByCategory(ctx context.Context, category string) ([]Item, error) {
	rows, err := q.db.Query(ctx, getByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Images,
			&i.Price,
			&i.Condition,
			&i.IsNegotiable,
			&i.PostedAt,
			&i.SoldAt,
			&i.Views,
			&i.Category,
			&i.Subcategory,
			&i.Fts,
			&i.Placeholder,
			&i.Likes,
			&i.Seller,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByIDs = `-- name: GetByIDs :many
SELECT
  id, name, description, images, price, condition, is_negotiable, posted_at, sold_at, views, category, subcategory, fts, placeholder, likes, seller
FROM
  "item"
WHERE
  id = ANY($1::bigint[])
`

func (q *Queries) GetByIDs(ctx context.Context, itemIds []int64) ([]Item, error) {
	rows, err := q.db.Query(ctx, getByIDs, itemIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Images,
			&i.Price,
			&i.Condition,
			&i.IsNegotiable,
			&i.PostedAt,
			&i.SoldAt,
			&i.Views,
			&i.Category,
			&i.Subcategory,
			&i.Fts,
			&i.Placeholder,
			&i.Likes,
			&i.Seller,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBySeller = `-- name: GetBySeller :many
SELECT
  id, name, description, images, price, condition, is_negotiable, posted_at, sold_at, views, category, subcategory, fts, placeholder, likes, seller
FROM
  "item"
WHERE
  seller = $1::uuid
ORDER BY
  posted_at DESC
`

func (q *Queries) GetBySeller(ctx context.Context, sellerID string) ([]Item, error) {
	rows, err := q.db.Query(ctx, getBySeller, sellerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Images,
			&i.Price,
			&i.Condition,
			&i.IsNegotiable,
			&i.PostedAt,
			&i.SoldAt,
			&i.Views,
			&i.Category,
			&i.Subcategory,
			&i.Fts,
			&i.Placeholder,
			&i.Likes,
			&i.Seller,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementLike = `-- name: IncrementLike :exec
UPDATE
  item
SET
  likes = likes + 1
WHERE
  id = $1
`

func (q *Queries) IncrementLike(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementLike, id)
	return err
}

const incrementView = `-- name: IncrementView :exec
UPDATE
  item
SET
  views = views + 1
WHERE
  id = $1
`

func (q *Queries) IncrementView(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementView, id)
	return err
}

const search = `-- name: Search :many
SELECT
 id, name, description, images, price, condition, is_negotiable, posted_at, sold_at, views, category, subcategory, fts, placeholder, likes, seller
FROM
  item
WHERE
  fts @@ websearch_to_tsquery($1)
`

func (q *Queries) Search(ctx context.Context, websearchToTsquery string) ([]Item, error) {
	rows, err := q.db.Query(ctx, search, websearchToTsquery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Images,
			&i.Price,
			&i.Condition,
			&i.IsNegotiable,
			&i.PostedAt,
			&i.SoldAt,
			&i.Views,
			&i.Category,
			&i.Subcategory,
			&i.Fts,
			&i.Placeholder,
			&i.Likes,
			&i.Seller,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByCategory = `-- name: SearchByCategory :many
SELECT
  id, name, description, images, price, condition, is_negotiable, posted_at, sold_at, views, category, subcategory, fts, placeholder, likes, seller
FROM
  item
WHERE
  category = $1 AND fts @@ to_tsquery($2)
`

type SearchByCategoryParams struct {
	Category  string `json:"category"`
	ToTsquery string `json:"to_tsquery"`
}

func (q *Queries) SearchByCategory(ctx context.Context, arg SearchByCategoryParams) ([]Item, error) {
	rows, err := q.db.Query(ctx, searchByCategory, arg.Category, arg.ToTsquery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Images,
			&i.Price,
			&i.Condition,
			&i.IsNegotiable,
			&i.PostedAt,
			&i.SoldAt,
			&i.Views,
			&i.Category,
			&i.Subcategory,
			&i.Fts,
			&i.Placeholder,
			&i.Likes,
			&i.Seller,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sell = `-- name: Sell :exec
UPDATE
  item
SET
  sold_at = $2
WHERE
  id = $1
`

type SellParams struct {
	ID     int64      `json:"id" param:"id"`
	SoldAt *time.Time `json:"sold_at"`
}

func (q *Queries) Sell(ctx context.Context, arg SellParams) error {
	_, err := q.db.Exec(ctx, sell, arg.ID, arg.SoldAt)
	return err
}

const update = `-- name: Update :one
UPDATE
  item
SET
  name = $2,
  description = $3,
  images = $4,
  price = $5,
  condition = $6,
  is_negotiable = $7,
  category = $8,
  subcategory = $9,
  placeholder = $10
WHERE
  id = $1
RETURNING id, name, description, images, price, condition, is_negotiable, posted_at, sold_at, views, category, subcategory, fts, placeholder, likes, seller
`

type UpdateParams struct {
	ID           int64    `json:"id" param:"id"`
	Name         string   `json:"name"`
	Description  string   `json:"description"`
	Images       []string `json:"images"`
	Price        float64  `json:"price"`
	Condition    int16    `json:"condition"`
	IsNegotiable bool     `json:"is_negotiable"`
	Category     string   `json:"category"`
	Subcategory  string   `json:"subcategory"`
	Placeholder  string   `json:"placeholder"`
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (Item, error) {
	row := q.db.QueryRow(ctx, update,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Images,
		arg.Price,
		arg.Condition,
		arg.IsNegotiable,
		arg.Category,
		arg.Subcategory,
		arg.Placeholder,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Images,
		&i.Price,
		&i.Condition,
		&i.IsNegotiable,
		&i.PostedAt,
		&i.SoldAt,
		&i.Views,
		&i.Category,
		&i.Subcategory,
		&i.Fts,
		&i.Placeholder,
		&i.Likes,
		&i.Seller,
	)
	return i, err
}
