// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package itemcategory

type ItemCategory struct {
	Name        string   `json:"name"`
	Subcategory []string `json:"subcategory"`
	Icon        string   `json:"icon"`
}
