// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package chatparticipant

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ChatParticipant struct {
	RoomID            string      `json:"room_id"`
	UserID            string      `json:"user_id"`
	LastReadMessageID pgtype.Int8 `json:"last_read_message_id"`
}
