// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package chatparticipant

type ChatParticipant struct {
	RoomID            string `json:"room_id"`
	UserID            string `json:"user_id"`
	LastReadMessageID *int64 `json:"last_read_message_id"`
}
