// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package chatparticipant

import (
	"context"
)

const create = `-- name: Create :exec
INSERT INTO
  chat.participant (room_id, user_id)
VALUES ($1, $2)
`

type CreateParams struct {
	RoomID string `json:"room_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) error {
	_, err := q.db.Exec(ctx, create, arg.RoomID, arg.UserID)
	return err
}
