# Generated by Django 5.2.1 on 2025-06-17 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='watch', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='condition',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='item',
            name='isNegotiable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='isSold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='postedAt',
            field=models.DateTimeField(auto_now_add=True, default='2023-10-01T12:00:00Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='seller',
            field=models.CharField(default='techguru123', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='subcategory',
            field=models.CharField(default='Watch', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
