# Generated by Django 5.2.1 on 2025-07-02 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_item_options_alter_item_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='image_urls',
            new_name='images',
        ),
    ]
