// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package itemitem

import (
	"context"
	"time"
)

const create = `-- name: Create :one
INSERT INTO
  item.item (name, description, images, price, condition, is_negotiable, category, subcategory, placeholder, seller)
VALUES
  ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, name, description, images, price, condition, is_negotiable, posted_at, sold_at, views, category, subcategory, fts, placeholder, likes, seller
`

type CreateParams struct {
	Name         string   `json:"name"`
	Description  string   `json:"description"`
	Images       []string `json:"images"`
	Price        float64  `json:"price"`
	Condition    int16    `json:"condition"`
	IsNegotiable bool     `json:"is_negotiable"`
	Category     string   `json:"category"`
	Subcategory  string   `json:"subcategory"`
	Placeholder  string   `json:"placeholder"`
	Seller       string   `json:"seller"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (ItemItem, error) {
	row := q.db.QueryRow(ctx, create,
		arg.Name,
		arg.Description,
		arg.Images,
		arg.Price,
		arg.Condition,
		arg.IsNegotiable,
		arg.Category,
		arg.Subcategory,
		arg.Placeholder,
		arg.Seller,
	)
	var i ItemItem
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Images,
		&i.Price,
		&i.Condition,
		&i.IsNegotiable,
		&i.PostedAt,
		&i.SoldAt,
		&i.Views,
		&i.Category,
		&i.Subcategory,
		&i.Fts,
		&i.Placeholder,
		&i.Likes,
		&i.Seller,
	)
	return i, err
}

const decrementLike = `-- name: DecrementLike :exec
UPDATE
  item.item
SET
  likes = GREATEST(likes - 1, 0)
WHERE
  id = $1
`

func (q *Queries) DecrementLike(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, decrementLike, id)
	return err
}

const delete = `-- name: Delete :exec
DELETE FROM
  item.item
WHERE
  id = $1
`

func (q *Queries) Delete(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, delete, id)
	return err
}

const get = `-- name: Get :one
SELECT
  id, name, description, images, price, condition, is_negotiable, posted_at, sold_at, views, category, subcategory, fts, placeholder, likes, seller
FROM
  item.item
WHERE
  id = $1
`

func (q *Queries) Get(ctx context.Context, id int64) (ItemItem, error) {
	row := q.db.QueryRow(ctx, get, id)
	var i ItemItem
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Images,
		&i.Price,
		&i.Condition,
		&i.IsNegotiable,
		&i.PostedAt,
		&i.SoldAt,
		&i.Views,
		&i.Category,
		&i.Subcategory,
		&i.Fts,
		&i.Placeholder,
		&i.Likes,
		&i.Seller,
	)
	return i, err
}

const getAll = `-- name: GetAll :many
SELECT
  id, name, description, images, price, condition, is_negotiable, posted_at, sold_at, views, category, subcategory, fts, placeholder, likes, seller
FROM
  item.item
ORDER BY 
  posted_at DESC
LIMIT 
  CAST($1 AS integer) OFFSET CAST($1 AS integer)*(CAST($2 AS integer)-1)
`

type GetAllParams struct {
	Size int32 `json:"size"`
	Page int32 `json:"page"`
}

func (q *Queries) GetAll(ctx context.Context, arg GetAllParams) ([]ItemItem, error) {
	rows, err := q.db.Query(ctx, getAll, arg.Size, arg.Page)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemItem{}
	for rows.Next() {
		var i ItemItem
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Images,
			&i.Price,
			&i.Condition,
			&i.IsNegotiable,
			&i.PostedAt,
			&i.SoldAt,
			&i.Views,
			&i.Category,
			&i.Subcategory,
			&i.Fts,
			&i.Placeholder,
			&i.Likes,
			&i.Seller,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBatch = `-- name: GetBatch :many
SELECT
  id, name, description, images, price, condition, is_negotiable, posted_at, sold_at, views, category, subcategory, fts, placeholder, likes, seller
FROM
  item.item
WHERE
  id = ANY($1::bigint[])
ORDER BY
  posted_at DESC
LIMIT 
  CAST($2 AS integer) OFFSET CAST($2 AS integer)*(CAST($3 AS integer)-1)
`

type GetBatchParams struct {
	ItemIds []int64 `json:"item_ids"`
	Size    int32   `json:"size"`
	Page    int32   `json:"page"`
}

func (q *Queries) GetBatch(ctx context.Context, arg GetBatchParams) ([]ItemItem, error) {
	rows, err := q.db.Query(ctx, getBatch, arg.ItemIds, arg.Size, arg.Page)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemItem{}
	for rows.Next() {
		var i ItemItem
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Images,
			&i.Price,
			&i.Condition,
			&i.IsNegotiable,
			&i.PostedAt,
			&i.SoldAt,
			&i.Views,
			&i.Category,
			&i.Subcategory,
			&i.Fts,
			&i.Placeholder,
			&i.Likes,
			&i.Seller,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByCategory = `-- name: GetByCategory :many
SELECT
  id, name, description, images, price, condition, is_negotiable, posted_at, sold_at, views, category, subcategory, fts, placeholder, likes, seller
FROM
  item.item
WHERE
  category = $1
ORDER BY 
  posted_at DESC
LIMIT 
  CAST($2 AS integer) OFFSET CAST($2 AS integer)*(CAST($3 AS integer)-1)
`

type GetByCategoryParams struct {
	Category string `json:"category"`
	Size     int32  `json:"size"`
	Page     int32  `json:"page"`
}

func (q *Queries) GetByCategory(ctx context.Context, arg GetByCategoryParams) ([]ItemItem, error) {
	rows, err := q.db.Query(ctx, getByCategory, arg.Category, arg.Size, arg.Page)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemItem{}
	for rows.Next() {
		var i ItemItem
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Images,
			&i.Price,
			&i.Condition,
			&i.IsNegotiable,
			&i.PostedAt,
			&i.SoldAt,
			&i.Views,
			&i.Category,
			&i.Subcategory,
			&i.Fts,
			&i.Placeholder,
			&i.Likes,
			&i.Seller,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBySeller = `-- name: GetBySeller :many
SELECT
  id, name, description, images, price, condition, is_negotiable, posted_at, sold_at, views, category, subcategory, fts, placeholder, likes, seller
FROM
  item.item
WHERE
  seller = $1::uuid
ORDER BY
  posted_at DESC
LIMIT 
  CAST($2 AS integer) OFFSET CAST($2 AS integer)*(CAST($3 AS integer)-1)
`

type GetBySellerParams struct {
	SellerID string `json:"seller_id"`
	Size     int32  `json:"size"`
	Page     int32  `json:"page"`
}

func (q *Queries) GetBySeller(ctx context.Context, arg GetBySellerParams) ([]ItemItem, error) {
	rows, err := q.db.Query(ctx, getBySeller, arg.SellerID, arg.Size, arg.Page)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemItem{}
	for rows.Next() {
		var i ItemItem
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Images,
			&i.Price,
			&i.Condition,
			&i.IsNegotiable,
			&i.PostedAt,
			&i.SoldAt,
			&i.Views,
			&i.Category,
			&i.Subcategory,
			&i.Fts,
			&i.Placeholder,
			&i.Likes,
			&i.Seller,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementLike = `-- name: IncrementLike :exec
UPDATE
  item.item
SET
  likes = likes + 1
WHERE
  id = $1
`

func (q *Queries) IncrementLike(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementLike, id)
	return err
}

const incrementView = `-- name: IncrementView :exec
UPDATE
  item.item
SET
  views = views + 1
WHERE
  id = $1
`

func (q *Queries) IncrementView(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementView, id)
	return err
}

const search = `-- name: Search :many
SELECT
 id, name, description, images, price, condition, is_negotiable, posted_at, sold_at, views, category, subcategory, fts, placeholder, likes, seller
FROM
  item.item
WHERE
  fts @@ websearch_to_tsquery($1)
LIMIT 
  CAST($2 AS integer) OFFSET CAST($2 AS integer)*(CAST($3 AS integer)-1)
`

type SearchParams struct {
	WebsearchToTsquery string `json:"websearch_to_tsquery"`
	Size               int32  `json:"size"`
	Page               int32  `json:"page"`
}

func (q *Queries) Search(ctx context.Context, arg SearchParams) ([]ItemItem, error) {
	rows, err := q.db.Query(ctx, search, arg.WebsearchToTsquery, arg.Size, arg.Page)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemItem{}
	for rows.Next() {
		var i ItemItem
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Images,
			&i.Price,
			&i.Condition,
			&i.IsNegotiable,
			&i.PostedAt,
			&i.SoldAt,
			&i.Views,
			&i.Category,
			&i.Subcategory,
			&i.Fts,
			&i.Placeholder,
			&i.Likes,
			&i.Seller,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchByCategory = `-- name: SearchByCategory :many
SELECT
  id, name, description, images, price, condition, is_negotiable, posted_at, sold_at, views, category, subcategory, fts, placeholder, likes, seller
FROM
  item.item
WHERE
  category = $1 AND fts @@ to_tsquery($2)
LIMIT 
  CAST($3 AS integer) OFFSET CAST($3 AS integer)*(CAST($4 AS integer)-1)
`

type SearchByCategoryParams struct {
	Category  string `json:"category"`
	ToTsquery string `json:"to_tsquery"`
	Size      int32  `json:"size"`
	Page      int32  `json:"page"`
}

func (q *Queries) SearchByCategory(ctx context.Context, arg SearchByCategoryParams) ([]ItemItem, error) {
	rows, err := q.db.Query(ctx, searchByCategory,
		arg.Category,
		arg.ToTsquery,
		arg.Size,
		arg.Page,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ItemItem{}
	for rows.Next() {
		var i ItemItem
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Images,
			&i.Price,
			&i.Condition,
			&i.IsNegotiable,
			&i.PostedAt,
			&i.SoldAt,
			&i.Views,
			&i.Category,
			&i.Subcategory,
			&i.Fts,
			&i.Placeholder,
			&i.Likes,
			&i.Seller,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sell = `-- name: Sell :exec
UPDATE
  item.item
SET
  sold_at = $2
WHERE
  id = $1
`

type SellParams struct {
	ID     int64      `json:"id"`
	SoldAt *time.Time `json:"sold_at"`
}

func (q *Queries) Sell(ctx context.Context, arg SellParams) error {
	_, err := q.db.Exec(ctx, sell, arg.ID, arg.SoldAt)
	return err
}

const update = `-- name: Update :one
UPDATE
  item.item
SET
  name = $2,
  description = $3,
  images = $4,
  price = $5,
  condition = $6,
  is_negotiable = $7,
  category = $8,
  subcategory = $9,
  placeholder = $10
WHERE
  id = $1
RETURNING id, name, description, images, price, condition, is_negotiable, posted_at, sold_at, views, category, subcategory, fts, placeholder, likes, seller
`

type UpdateParams struct {
	ID           int64    `json:"id"`
	Name         string   `json:"name"`
	Description  string   `json:"description"`
	Images       []string `json:"images"`
	Price        float64  `json:"price"`
	Condition    int16    `json:"condition"`
	IsNegotiable bool     `json:"is_negotiable"`
	Category     string   `json:"category"`
	Subcategory  string   `json:"subcategory"`
	Placeholder  string   `json:"placeholder"`
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (ItemItem, error) {
	row := q.db.QueryRow(ctx, update,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Images,
		arg.Price,
		arg.Condition,
		arg.IsNegotiable,
		arg.Category,
		arg.Subcategory,
		arg.Placeholder,
	)
	var i ItemItem
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Images,
		&i.Price,
		&i.Condition,
		&i.IsNegotiable,
		&i.PostedAt,
		&i.SoldAt,
		&i.Views,
		&i.Category,
		&i.Subcategory,
		&i.Fts,
		&i.Placeholder,
		&i.Likes,
		&i.Seller,
	)
	return i, err
}
