version: 3

dotenv:
  - .env
tasks:
  run:
    cmds:
      - go run ./cmd/server
    silent: true

  test:
    cmds:
      - go test ./... -v
    silent: true

  docs:
    cmds:
      - swag fmt
      - swag init --dir ./internal/api,./internal/db/item,./internal/db/chat,./internal/db/user --generalInfo api.go --parseInternal --parseDependency
    silent: true

  sql:
    cmds:
      - sqlc generate
    silent: true

  datagen:
    cmds:
      - go run ./cmd/datagen
    silent: true
