version: 3

dotenv:
  - .env
tasks:
  run:
    cmds:
      - go run ./cmd/server/main.go
    silent: true

  test:
    cmds:
      - go test ./... -v
    silent: true

  docs:
    cmds:
      - swag fmt
      - swag init --dir ./internal/api,./sql/item,./sql/category,./sql/user --generalInfo api.go --parseInternal --parseDependency
    silent: true

  sql:
    cmds:
      - sqlc generate
    silent: true
