// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package chatmessage

import (
	"context"
)

const create = `-- name: Create :exec
INSERT INTO
  chat.message(id, room_id, sent_by, body)
VALUES
  ($1, $2, $3, $4)
`

type CreateParams struct {
	ID     int64  `json:"id"`
	RoomID string `json:"room_id"`
	SentBy string `json:"sent_by"`
	Body   string `json:"body"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) error {
	_, err := q.db.Exec(ctx, create,
		arg.ID,
		arg.RoomID,
		arg.SentBy,
		arg.Body,
	)
	return err
}

const delete = `-- name: Delete :exec
DELETE FROM
  chat.message
WHERE
  id = $1
`

func (q *Queries) Delete(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, delete, id)
	return err
}

const editMessage = `-- name: EditMessage :exec
UPDATE
  chat.message
SET
  body = $2, edited = true
WHERE
  id = $1
`

type EditMessageParams struct {
	ID   int64  `json:"id"`
	Body string `json:"body"`
}

func (q *Queries) EditMessage(ctx context.Context, arg EditMessageParams) error {
	_, err := q.db.Exec(ctx, editMessage, arg.ID, arg.Body)
	return err
}

const getByID = `-- name: GetByID :one
SELECT
  room_id, sent_by, body, id, edited, sent_at
FROM
  chat.message
WHERE
  id = $1
`

func (q *Queries) GetByID(ctx context.Context, id int64) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i ChatMessage
	err := row.Scan(
		&i.RoomID,
		&i.SentBy,
		&i.Body,
		&i.ID,
		&i.Edited,
		&i.SentAt,
	)
	return i, err
}

const getLatestMessage = `-- name: GetLatestMessage :one
SELECT 
  room_id, sent_by, body, id, edited, sent_at
FROM
  chat.message
WHERE
  room_id = $1
ORDER BY 
  sent_at DESC
LIMIT 1
`

func (q *Queries) GetLatestMessage(ctx context.Context, roomID string) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, getLatestMessage, roomID)
	var i ChatMessage
	err := row.Scan(
		&i.RoomID,
		&i.SentBy,
		&i.Body,
		&i.ID,
		&i.Edited,
		&i.SentAt,
	)
	return i, err
}

const getMany = `-- name: GetMany :many
SELECT
  room_id, sent_by, body, id, edited, sent_at
FROM
  chat.message
WHERE
  room_id = $1
ORDER BY
  sent_at DESC
LIMIT 
  10 OFFSET 10*(CAST($2 AS integer)-1)
`

type GetManyParams struct {
	RoomID string `json:"room_id"`
	Page   int32  `json:"page"`
}

func (q *Queries) GetMany(ctx context.Context, arg GetManyParams) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, getMany, arg.RoomID, arg.Page)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMessage{}
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.RoomID,
			&i.SentBy,
			&i.Body,
			&i.ID,
			&i.Edited,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
