// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package userverify

import (
	"time"
)

type UserVerify struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	ExpiredAt time.Time `json:"expired_at"`
}
