// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqluser

import (
	"context"
)

const create = `-- name: Create :one
INSERT INTO
  "user" (email, password)
VALUES
  ($1, $2)
RETURNING email, password
`

type CreateParams struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (User, error) {
	row := q.db.QueryRow(ctx, create, arg.Email, arg.Password)
	var i User
	err := row.Scan(&i.Email, &i.Password)
	return i, err
}

const get = `-- name: Get :one
SELECT
  email, password
FROM
  "user"
WHERE
  email = $1
`

func (q *Queries) Get(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, get, email)
	var i User
	err := row.Scan(&i.Email, &i.Password)
	return i, err
}

const getMany = `-- name: GetMany :many
SELECT
  email, password
FROM
  "user"
`

func (q *Queries) GetMany(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getMany)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.Email, &i.Password); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
