// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package useruser

import (
	"time"
)

type UserLiked struct {
	UserID    string    `json:"user_id"`
	ItemID    int64     `json:"item_id"`
	CreatedAt time.Time `json:"created_at"`
}

type UserUser struct {
	Email     string `json:"email"`
	Password  string `json:"password"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	ID        string `json:"id"`
	Verified  bool   `json:"verified"`
	Avatar    string `json:"avatar"`
}

type UserViewed struct {
	UserID    string    `json:"user_id"`
	ItemID    int64     `json:"item_id"`
	CreatedAt time.Time `json:"created_at"`
}
