// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package useruser

type UserUser struct {
	Email      string  `json:"email"`
	Password   string  `json:"password"`
	LikedItems []int64 `json:"liked_items"`
	FirstName  string  `json:"first_name"`
	LastName   string  `json:"last_name"`
	ID         string  `json:"id"`
}
