// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package useruser

import (
	"context"
)

const addLikedItem = `-- name: AddLikedItem :exec
UPDATE
  "user"."user"
SET
  liked_items = array_append(liked_items, $1::bigint)
WHERE
  id = $2
  AND NOT liked_items @> ARRAY[$1::bigint]
`

type AddLikedItemParams struct {
	ItemID int64  `json:"item_id"`
	ID     string `json:"id"`
}

func (q *Queries) AddLikedItem(ctx context.Context, arg AddLikedItemParams) error {
	_, err := q.db.Exec(ctx, addLikedItem, arg.ItemID, arg.ID)
	return err
}

const create = `-- name: Create :one
INSERT INTO
  "user"."user" (email, password, first_name, last_name)
VALUES
  ($1, $2, $3, $4)
RETURNING email, password, liked_items, first_name, last_name, id, avatar
`

type CreateParams struct {
	Email     string `json:"email"`
	Password  string `json:"password"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (UserUser, error) {
	row := q.db.QueryRow(ctx, create,
		arg.Email,
		arg.Password,
		arg.FirstName,
		arg.LastName,
	)
	var i UserUser
	err := row.Scan(
		&i.Email,
		&i.Password,
		&i.LikedItems,
		&i.FirstName,
		&i.LastName,
		&i.ID,
		&i.Avatar,
	)
	return i, err
}

const deleteLikedItem = `-- name: DeleteLikedItem :exec
UPDATE
  "user"."user"
SET
  liked_items = array_remove(liked_items, $1::bigint)
WHERE
  id = $2
  AND (liked_items @> ARRAY[$1::bigint])
`

type DeleteLikedItemParams struct {
	ItemID int64  `json:"item_id"`
	ID     string `json:"id"`
}

func (q *Queries) DeleteLikedItem(ctx context.Context, arg DeleteLikedItemParams) error {
	_, err := q.db.Exec(ctx, deleteLikedItem, arg.ItemID, arg.ID)
	return err
}

const get = `-- name: Get :one
SELECT
  email, password, liked_items, first_name, last_name, id, avatar
FROM
  "user"."user"
WHERE
  email = $1
`

func (q *Queries) Get(ctx context.Context, email string) (UserUser, error) {
	row := q.db.QueryRow(ctx, get, email)
	var i UserUser
	err := row.Scan(
		&i.Email,
		&i.Password,
		&i.LikedItems,
		&i.FirstName,
		&i.LastName,
		&i.ID,
		&i.Avatar,
	)
	return i, err
}

const getByID = `-- name: GetByID :one
SELECT
  email, password, liked_items, first_name, last_name, id, avatar
FROM
  "user"."user"
WHERE
  id = $1
`

func (q *Queries) GetByID(ctx context.Context, id string) (UserUser, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i UserUser
	err := row.Scan(
		&i.Email,
		&i.Password,
		&i.LikedItems,
		&i.FirstName,
		&i.LastName,
		&i.ID,
		&i.Avatar,
	)
	return i, err
}

const getLikedItems = `-- name: GetLikedItems :one
SELECT
  liked_items
FROM 
  "user"."user"
WHERE
  id = $1
`

func (q *Queries) GetLikedItems(ctx context.Context, id string) ([]int64, error) {
	row := q.db.QueryRow(ctx, getLikedItems, id)
	var liked_items []int64
	err := row.Scan(&liked_items)
	return liked_items, err
}

const getMany = `-- name: GetMany :many
SELECT
  email, password, liked_items, first_name, last_name, id, avatar
FROM
  "user"."user"
`

func (q *Queries) GetMany(ctx context.Context) ([]UserUser, error) {
	rows, err := q.db.Query(ctx, getMany)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserUser{}
	for rows.Next() {
		var i UserUser
		if err := rows.Scan(
			&i.Email,
			&i.Password,
			&i.LikedItems,
			&i.FirstName,
			&i.LastName,
			&i.ID,
			&i.Avatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAvatar = `-- name: UpdateAvatar :exec
UPDATE
  "user"."user"
SET
  avatar = $2
WHERE
  id = $1
`

type UpdateAvatarParams struct {
	ID     string `json:"id"`
	Avatar string `json:"avatar"`
}

func (q *Queries) UpdateAvatar(ctx context.Context, arg UpdateAvatarParams) error {
	_, err := q.db.Exec(ctx, updateAvatar, arg.ID, arg.Avatar)
	return err
}
