// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package useruser

import (
	"context"
)

const create = `-- name: Create :one
INSERT INTO
  "user"."user" (email, password, first_name, last_name)
VALUES
  ($1, $2, $3, $4)
RETURNING email, password, first_name, last_name, id
`

type CreateParams struct {
	Email     string `json:"email"`
	Password  string `json:"password"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (UserUser, error) {
	row := q.db.QueryRow(ctx, create,
		arg.Email,
		arg.Password,
		arg.FirstName,
		arg.LastName,
	)
	var i UserUser
	err := row.Scan(
		&i.Email,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.ID,
	)
	return i, err
}

const get = `-- name: Get :one
SELECT
  email, password, first_name, last_name, id
FROM
  "user"."user"
WHERE
  email = $1
`

func (q *Queries) Get(ctx context.Context, email string) (UserUser, error) {
	row := q.db.QueryRow(ctx, get, email)
	var i UserUser
	err := row.Scan(
		&i.Email,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.ID,
	)
	return i, err
}

const getByID = `-- name: GetByID :one
SELECT
  email, password, first_name, last_name, id
FROM
  "user"."user"
WHERE
  id = $1
`

func (q *Queries) GetByID(ctx context.Context, id string) (UserUser, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i UserUser
	err := row.Scan(
		&i.Email,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.ID,
	)
	return i, err
}

const getMany = `-- name: GetMany :many
SELECT
  email, password, first_name, last_name, id
FROM
  "user"."user"
`

func (q *Queries) GetMany(ctx context.Context) ([]UserUser, error) {
	rows, err := q.db.Query(ctx, getMany)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserUser{}
	for rows.Next() {
		var i UserUser
		if err := rows.Scan(
			&i.Email,
			&i.Password,
			&i.FirstName,
			&i.LastName,
			&i.ID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
