create schema item;
set search_path to item;

create table item.item (
  id bigint generated by default as identity not null,
  name text not null default ''::text,
  description text not null default ''::text,
  images text[] not null,
  price double precision not null default '0'::double precision,
  condition smallint not null default '0'::smallint,
  is_negotiable boolean not null default false,
  posted_at timestamp with time zone not null default now(),
  sold_at timestamp with time zone null,
  views bigint not null default '0'::bigint,
  category text not null,
  subcategory text not null,
  fts tsvector GENERATED ALWAYS as (
    to_tsvector(
      'english'::regconfig,
      ((description || ' '::text) || name)
    )
  ) STORED null,
  placeholder text not null default '''''::text'::text,
  likes bigint not null default '0'::bigint,
  seller uuid not null,
  constraint item_pkey primary key (id)
  -- constraint item_category_fkey foreign KEY (category) references item.category (name) on update CASCADE on delete set default,
  -- constraint item_seller_fkey foreign KEY (seller) references "user"."user" (id) on update CASCADE on delete set default
) TABLESPACE pg_default;

create index IF not exists item_fts on item.item using gin (fts) TABLESPACE pg_default;
