// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package item

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Item struct {
	ID           int64              `json:"id" param:"id"`
	Name         string             `json:"name"`
	Description  string             `json:"description"`
	Images       []string           `json:"images"`
	Price        float64            `json:"price"`
	Condition    int16              `json:"condition"`
	IsNegotiable bool               `json:"is_negotiable"`
	PostedAt     time.Time          `json:"posted_at"`
	SoldAt       pgtype.Timestamptz `json:"sold_at"`
	Views        int64              `json:"views"`
	Category     string             `json:"category"`
	SubCategory  string             `json:"sub_category"`
}
