// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package item

import (
	"context"
	"time"
)

const create = `-- name: Create :one
INSERT INTO
  item (name, description, images, price, condition, is_negotiable, category, sub_category)
VALUES
  ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, description, images, price, condition, is_negotiable, posted_at, sold_at, views, category, sub_category, fts
`

type CreateParams struct {
	Name         string   `json:"name"`
	Description  string   `json:"description"`
	Images       []string `json:"images"`
	Price        float64  `json:"price"`
	Condition    int16    `json:"condition"`
	IsNegotiable bool     `json:"is_negotiable"`
	Category     string   `json:"category"`
	SubCategory  string   `json:"sub_category"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (Item, error) {
	row := q.db.QueryRow(ctx, create,
		arg.Name,
		arg.Description,
		arg.Images,
		arg.Price,
		arg.Condition,
		arg.IsNegotiable,
		arg.Category,
		arg.SubCategory,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Images,
		&i.Price,
		&i.Condition,
		&i.IsNegotiable,
		&i.PostedAt,
		&i.SoldAt,
		&i.Views,
		&i.Category,
		&i.SubCategory,
		&i.Fts,
	)
	return i, err
}

const delete = `-- name: Delete :exec
DELETE FROM
  item
WHERE
  id = $1
`

func (q *Queries) Delete(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, delete, id)
	return err
}

const get = `-- name: Get :one
SELECT
  id, name, description, images, price, condition, is_negotiable, posted_at, sold_at, views, category, sub_category
FROM
  item
WHERE
  id = $1
`

type GetRow struct {
	ID           int64      `json:"id" param:"id"`
	Name         string     `json:"name"`
	Description  string     `json:"description"`
	Images       []string   `json:"images"`
	Price        float64    `json:"price"`
	Condition    int16      `json:"condition"`
	IsNegotiable bool       `json:"is_negotiable"`
	PostedAt     time.Time  `json:"posted_at"`
	SoldAt       *time.Time `json:"sold_at"`
	Views        int64      `json:"views"`
	Category     string     `json:"category"`
	SubCategory  string     `json:"sub_category"`
}

func (q *Queries) Get(ctx context.Context, id int64) (GetRow, error) {
	row := q.db.QueryRow(ctx, get, id)
	var i GetRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Images,
		&i.Price,
		&i.Condition,
		&i.IsNegotiable,
		&i.PostedAt,
		&i.SoldAt,
		&i.Views,
		&i.Category,
		&i.SubCategory,
	)
	return i, err
}

const getAll = `-- name: GetAll :many
SELECT
  id, name, description, images, price, condition, is_negotiable, posted_at, sold_at, views, category, sub_category, fts
 -- id, name, description, images, price, condition, is_negotiable, posted_at, sold_at, views, category, sub_category
FROM
  item
`

func (q *Queries) GetAll(ctx context.Context) ([]Item, error) {
	rows, err := q.db.Query(ctx, getAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Images,
			&i.Price,
			&i.Condition,
			&i.IsNegotiable,
			&i.PostedAt,
			&i.SoldAt,
			&i.Views,
			&i.Category,
			&i.SubCategory,
			&i.Fts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementView = `-- name: IncrementView :exec
UPDATE
  item
SET
  views = views + 1
WHERE
  id = $1
`

func (q *Queries) IncrementView(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementView, id)
	return err
}

const search = `-- name: Search :many
SELECT
 id, name, description, images, price, condition, is_negotiable, posted_at, sold_at, views, category, sub_category, fts
  -- id, name, description, images, price, condition, is_negotiable, posted_at, sold_at, views, category, sub_category
FROM
  item
WHERE
  fts @@ to_tsquery($1)
`

func (q *Queries) Search(ctx context.Context, toTsquery string) ([]Item, error) {
	rows, err := q.db.Query(ctx, search, toTsquery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Images,
			&i.Price,
			&i.Condition,
			&i.IsNegotiable,
			&i.PostedAt,
			&i.SoldAt,
			&i.Views,
			&i.Category,
			&i.SubCategory,
			&i.Fts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sell = `-- name: Sell :exec

UPDATE
  item
SET
  sold_at = $2
WHERE
  id = $1
`

type SellParams struct {
	ID     int64      `json:"id" param:"id"`
	SoldAt *time.Time `json:"sold_at"`
}

// RETURNING id, name, description, images, price, condition, is_negotiable, posted_at, sold_at, views, category, sub_category;
func (q *Queries) Sell(ctx context.Context, arg SellParams) error {
	_, err := q.db.Exec(ctx, sell, arg.ID, arg.SoldAt)
	return err
}

const update = `-- name: Update :one

UPDATE
  item
SET
  name = $2,
  description = $3,
  images = $4,
  price = $5,
  condition = $6,
  is_negotiable = $7,
  views = $8
WHERE
  id = $1
RETURNING id, name, description, images, price, condition, is_negotiable, posted_at, sold_at, views, category, sub_category, fts
`

type UpdateParams struct {
	ID           int64    `json:"id" param:"id"`
	Name         string   `json:"name"`
	Description  string   `json:"description"`
	Images       []string `json:"images"`
	Price        float64  `json:"price"`
	Condition    int16    `json:"condition"`
	IsNegotiable bool     `json:"is_negotiable"`
	Views        int64    `json:"views"`
}

// RETURNING id, name, description, images, price, condition, is_negotiable, posted_at, sold_at, views, category, sub_category;
func (q *Queries) Update(ctx context.Context, arg UpdateParams) (Item, error) {
	row := q.db.QueryRow(ctx, update,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Images,
		arg.Price,
		arg.Condition,
		arg.IsNegotiable,
		arg.Views,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Images,
		&i.Price,
		&i.Condition,
		&i.IsNegotiable,
		&i.PostedAt,
		&i.SoldAt,
		&i.Views,
		&i.Category,
		&i.SubCategory,
		&i.Fts,
	)
	return i, err
}
