CREATE TABLE public.item (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  name text NOT NULL DEFAULT ''::text,
  description text NOT NULL DEFAULT ''::text,
  images text[] NOT NULL,
  price double precision NOT NULL DEFAULT '0'::double precision,
  condition smallint NOT NULL DEFAULT '0'::smallint,
  is_negotiable boolean NOT NULL DEFAULT false,
  posted_at timestamp with time zone NOT NULL DEFAULT now(),
  sold_at timestamp with time zone,
  views bigint NOT NULL DEFAULT '0'::bigint,
  category text NOT NULL,
  subcategory text NOT NULL,
  fts tsvector GENERATED ALWAYS AS (to_tsvector('english'::regconfig, ((description || ' '::text) || name))) STORED,
  placeholder text NOT NULL default ''::text,
  likes bigint NOT NULL DEFAULT '0'::bigint,
  seller uuid not null,
  constraint item_pkey primary key (id),
  constraint item_category_fkey foreign KEY (category) references category (name) on update RESTRICT on delete RESTRICT,
  constraint item_seller_fkey foreign KEY (seller) references "user" (id) on update CASCADE on delete CASCADE
);