// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package userblock

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type UserBlock struct {
	BlockerID string           `json:"blocker_id"`
	BlockedID string           `json:"blocked_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
