// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package userblock

import (
	"context"
)

const block = `-- name: Block :exec
INSERT INTO
"user"."block" (blocker_id, blocked_id)
VALUES
($1, $2)
RETURNING blocker_id, blocked_id, created_at
`

type BlockParams struct {
	BlockerID string `json:"blocker_id"`
	BlockedID string `json:"blocked_id"`
}

func (q *Queries) Block(ctx context.Context, arg BlockParams) error {
	_, err := q.db.Exec(ctx, block, arg.BlockerID, arg.BlockedID)
	return err
}

const getBlocksByBlockedID = `-- name: GetBlocksByBlockedID :many
SELECT
  blocker_id
FROM
  "user"."block"
WHERE blocked_id=$1
`

func (q *Queries) GetBlocksByBlockedID(ctx context.Context, blockedID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getBlocksByBlockedID, blockedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var blocker_id string
		if err := rows.Scan(&blocker_id); err != nil {
			return nil, err
		}
		items = append(items, blocker_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlocksByBlockerID = `-- name: GetBlocksByBlockerID :many
SELECT
  blocked_id
FROM
  "user"."block"
WHERE blocker_id=$1
`

func (q *Queries) GetBlocksByBlockerID(ctx context.Context, blockerID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getBlocksByBlockerID, blockerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var blocked_id string
		if err := rows.Scan(&blocked_id); err != nil {
			return nil, err
		}
		items = append(items, blocked_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unblock = `-- name: Unblock :exec
DELETE FROM
"user"."block"
WHERE
blocker_id = $1 AND blocked_id = $2
RETURNING blocker_id, blocked_id, created_at
`

type UnblockParams struct {
	BlockerID string `json:"blocker_id"`
	BlockedID string `json:"blocked_id"`
}

func (q *Queries) Unblock(ctx context.Context, arg UnblockParams) error {
	_, err := q.db.Exec(ctx, unblock, arg.BlockerID, arg.BlockedID)
	return err
}
