// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package chatroom

type ChatRoom struct {
	ID           string   `json:"id"`
	MessageCount int64    `json:"message_count"`
	Participants []string `json:"participants"`
}
