// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package chatroom

type ChatRoom struct {
	ID           string   `json:"id"`
	Participants []string `json:"participants"`
	Messages     []int64  `json:"messages"`
}
