// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package chatroom

import (
	"context"
)

const addParticipant = `-- name: AddParticipant :exec
UPDATE
  chat.room
SET
  participants = array_append(participants, $1::uuid)
WHERE
  id = $2
  AND NOT participants @> ARRAY[$1::uuid]
`

type AddParticipantParams struct {
	UserID string `json:"user_id"`
	RoomID string `json:"room_id"`
}

func (q *Queries) AddParticipant(ctx context.Context, arg AddParticipantParams) error {
	_, err := q.db.Exec(ctx, addParticipant, arg.UserID, arg.RoomID)
	return err
}

const createRoom = `-- name: CreateRoom :one
INSERT INTO
  chat.room (participants)
VALUES
  ($1)
RETURNING id
`

func (q *Queries) CreateRoom(ctx context.Context, participants []string) (string, error) {
	row := q.db.QueryRow(ctx, createRoom, participants)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteRoom = `-- name: DeleteRoom :exec
DELETE FROM
  chat.room
WHERE
  id = $1
`

func (q *Queries) DeleteRoom(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteRoom, id)
	return err
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT
  id, title, participants
FROM
  chat.room
WHERE
  id = $1
`

func (q *Queries) GetRoomByID(ctx context.Context, id string) (ChatRoom, error) {
	row := q.db.QueryRow(ctx, getRoomByID, id)
	var i ChatRoom
	err := row.Scan(&i.ID, &i.Title, &i.Participants)
	return i, err
}

const removeParticipant = `-- name: RemoveParticipant :exec
UPDATE
  chat.room
SET
  participants = array_remove(participants, $1::uuid)
WHERE
  id = $2
  AND participants @> ARRAY[$1::uuid]
`

type RemoveParticipantParams struct {
	UserID string `json:"user_id"`
	RoomID string `json:"room_id"`
}

func (q *Queries) RemoveParticipant(ctx context.Context, arg RemoveParticipantParams) error {
	_, err := q.db.Exec(ctx, removeParticipant, arg.UserID, arg.RoomID)
	return err
}
