// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package chatroom

import (
	"context"
)

const addMessage = `-- name: AddMessage :exec
UPDATE
  chat.room
SET
  messages = array_append(messages, $2::bigint)
WHERE
  id = $1
  AND NOT (messages @> ARRAY[$2::bigint])
`

type AddMessageParams struct {
	ID        string `json:"id"`
	MessageID int64  `json:"message_id"`
}

func (q *Queries) AddMessage(ctx context.Context, arg AddMessageParams) error {
	_, err := q.db.Exec(ctx, addMessage, arg.ID, arg.MessageID)
	return err
}

const addParticipant = `-- name: AddParticipant :exec
UPDATE
  chat.room
SET
  participants = $1
WHERE
  id = $2
`

type AddParticipantParams struct {
	Participants []string `json:"participants"`
	ID           string   `json:"id"`
}

func (q *Queries) AddParticipant(ctx context.Context, arg AddParticipantParams) error {
	_, err := q.db.Exec(ctx, addParticipant, arg.Participants, arg.ID)
	return err
}

const createRoom = `-- name: CreateRoom :one
INSERT INTO
  "chat"."room" (participants)
VALUES
  ($1)
RETURNING id
`

func (q *Queries) CreateRoom(ctx context.Context, participants []string) (string, error) {
	row := q.db.QueryRow(ctx, createRoom, participants)
	var id string
	err := row.Scan(&id)
	return id, err
}

const removeParticipant = `-- name: RemoveParticipant :exec
UPDATE
  chat.room
SET
  participants = $1
WHERE
  id = $2
`

type RemoveParticipantParams struct {
	Participants []string `json:"participants"`
	ID           string   `json:"id"`
}

func (q *Queries) RemoveParticipant(ctx context.Context, arg RemoveParticipantParams) error {
	_, err := q.db.Exec(ctx, removeParticipant, arg.Participants, arg.ID)
	return err
}
