// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package userdb

import (
	"context"
)

const addLikedItem = `-- name: AddLikedItem :one
UPDATE
  "user"
SET
  liked_items = array_append(liked_items, $1::bigint)
WHERE
  id = $2
  AND NOT liked_items @> ARRAY[$1::bigint]
RETURNING liked_items
`

type AddLikedItemParams struct {
	ItemID int64  `json:"item_id"`
	ID     string `json:"id"`
}

func (q *Queries) AddLikedItem(ctx context.Context, arg AddLikedItemParams) ([]int64, error) {
	row := q.db.QueryRow(ctx, addLikedItem, arg.ItemID, arg.ID)
	var liked_items []int64
	err := row.Scan(&liked_items)
	return liked_items, err
}

const create = `-- name: Create :one
INSERT INTO
  "user" (email, password, first_name, last_name)
VALUES
  ($1, $2, $3, $4)
RETURNING email, password, liked_items, first_name, last_name, id
`

type CreateParams struct {
	Email     string `json:"email"`
	Password  string `json:"password"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (User, error) {
	row := q.db.QueryRow(ctx, create,
		arg.Email,
		arg.Password,
		arg.FirstName,
		arg.LastName,
	)
	var i User
	err := row.Scan(
		&i.Email,
		&i.Password,
		&i.LikedItems,
		&i.FirstName,
		&i.LastName,
		&i.ID,
	)
	return i, err
}

const deleteLikedItem = `-- name: DeleteLikedItem :one
UPDATE
  "user"
SET
  liked_items = array_remove(liked_items, $1::bigint)
WHERE
  id = $2
  AND (liked_items @> ARRAY[$1::bigint])
RETURNING liked_items
`

type DeleteLikedItemParams struct {
	ItemID int64  `json:"item_id"`
	ID     string `json:"id"`
}

func (q *Queries) DeleteLikedItem(ctx context.Context, arg DeleteLikedItemParams) ([]int64, error) {
	row := q.db.QueryRow(ctx, deleteLikedItem, arg.ItemID, arg.ID)
	var liked_items []int64
	err := row.Scan(&liked_items)
	return liked_items, err
}

const get = `-- name: Get :one
SELECT
  email, password, liked_items, first_name, last_name, id
FROM
  "user"
WHERE
  id = $1
`

func (q *Queries) Get(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, get, id)
	var i User
	err := row.Scan(
		&i.Email,
		&i.Password,
		&i.LikedItems,
		&i.FirstName,
		&i.LastName,
		&i.ID,
	)
	return i, err
}

const getFullUserByID = `-- name: GetFullUserByID :one
SELECT
  id, email, liked_items, first_name, last_name
FROM
  "user"
WHERE
  id = $1
`

type GetFullUserByIDRow struct {
	ID         string  `json:"id"`
	Email      string  `json:"email"`
	LikedItems []int64 `json:"liked_items"`
	FirstName  string  `json:"first_name"`
	LastName   string  `json:"last_name"`
}

func (q *Queries) GetFullUserByID(ctx context.Context, id string) (GetFullUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getFullUserByID, id)
	var i GetFullUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.LikedItems,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}

const getLikedItems = `-- name: GetLikedItems :one
SELECT
  liked_items
FROM 
  "user"
WHERE
  id = $1
`

func (q *Queries) GetLikedItems(ctx context.Context, id string) ([]int64, error) {
	row := q.db.QueryRow(ctx, getLikedItems, id)
	var liked_items []int64
	err := row.Scan(&liked_items)
	return liked_items, err
}

const getMany = `-- name: GetMany :many
SELECT
  email, password, liked_items, first_name, last_name, id
FROM
  "user"
`

func (q *Queries) GetMany(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getMany)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Email,
			&i.Password,
			&i.LikedItems,
			&i.FirstName,
			&i.LastName,
			&i.ID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSellerByID = `-- name: GetSellerByID :one
SELECT
  id, first_name, last_name
FROM
  "user"
WHERE
  id = $1
`

type GetSellerByIDRow struct {
	ID        string `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
}

func (q *Queries) GetSellerByID(ctx context.Context, id string) (GetSellerByIDRow, error) {
	row := q.db.QueryRow(ctx, getSellerByID, id)
	var i GetSellerByIDRow
	err := row.Scan(&i.ID, &i.FirstName, &i.LastName)
	return i, err
}
