// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package category

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	Name        string      `json:"name"`
	Subcategory []string    `json:"subcategory"`
	Icon        pgtype.Text `json:"icon"`
}
