// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package category

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const create = `-- name: Create :one
INSERT INTO
  category (name, subcategory, icon)
VALUES
  ($1, $2, $3)
RETURNING name, subcategory, icon
`

type CreateParams struct {
	Name        string      `json:"name"`
	Subcategory []string    `json:"subcategory"`
	Icon        pgtype.Text `json:"icon"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (Category, error) {
	row := q.db.QueryRow(ctx, create, arg.Name, arg.Subcategory, arg.Icon)
	var i Category
	err := row.Scan(&i.Name, &i.Subcategory, &i.Icon)
	return i, err
}

const getAll = `-- name: GetAll :many
SELECT
  name, subcategory, icon
FROM
  category
`

func (q *Queries) GetAll(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, getAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.Name, &i.Subcategory, &i.Icon); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
