// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package userliked

import (
	"time"
)

type UserLiked struct {
	UserID    string    `json:"user_id"`
	ItemID    int64     `json:"item_id"`
	CreatedAt time.Time `json:"created_at"`
}
