// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package userliked

import (
	"context"
)

const like = `-- name: Like :exec
INSERT INTO
"user"."liked" (user_id, item_id)
VALUES
($1, $2)
RETURNING user_id, item_id, created_at
`

type LikeParams struct {
	UserID string `json:"user_id"`
	ItemID int64  `json:"item_id"`
}

func (q *Queries) Like(ctx context.Context, arg LikeParams) error {
	_, err := q.db.Exec(ctx, like, arg.UserID, arg.ItemID)
	return err
}

const unlike = `-- name: Unlike :exec
DELETE FROM
"user"."liked"
WHERE
user_id = $1 AND item_id = $2
RETURNING user_id, item_id, created_at
`

type UnlikeParams struct {
	UserID string `json:"user_id"`
	ItemID int64  `json:"item_id"`
}

func (q *Queries) Unlike(ctx context.Context, arg UnlikeParams) error {
	_, err := q.db.Exec(ctx, unlike, arg.UserID, arg.ItemID)
	return err
}
