// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package userliked

import (
	"context"
	"time"
)

const create = `-- name: Create :one
INSERT INTO
"user"."liked" (user_id, item_id, created_at)
VALUES
($1, $2, $3)
RETURNING user_id, item_id, created_at
`

type CreateParams struct {
	UserID    string    `json:"user_id"`
	ItemID    int64     `json:"item_id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (UserLiked, error) {
	row := q.db.QueryRow(ctx, create, arg.UserID, arg.ItemID, arg.CreatedAt)
	var i UserLiked
	err := row.Scan(&i.UserID, &i.ItemID, &i.CreatedAt)
	return i, err
}

const delete = `-- name: Delete :one
DELETE FROM
"user"."liked"
WHERE
user_id = $1
RETURNING user_id, item_id, created_at
`

func (q *Queries) Delete(ctx context.Context, userID string) (UserLiked, error) {
	row := q.db.QueryRow(ctx, delete, userID)
	var i UserLiked
	err := row.Scan(&i.UserID, &i.ItemID, &i.CreatedAt)
	return i, err
}

const getAll = `-- name: GetAll :many
SELECT
  user_id, item_id, created_at
FROM
  "user"."liked"
`

func (q *Queries) GetAll(ctx context.Context) ([]UserLiked, error) {
	rows, err := q.db.Query(ctx, getAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserLiked{}
	for rows.Next() {
		var i UserLiked
		if err := rows.Scan(&i.UserID, &i.ItemID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
