// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package userliked

import (
	"context"
)

const getAll = `-- name: GetAll :many
SELECT
  user_id, item_id, created_at
FROM
  "user"."liked"
`

func (q *Queries) GetAll(ctx context.Context) ([]UserLiked, error) {
	rows, err := q.db.Query(ctx, getAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserLiked{}
	for rows.Next() {
		var i UserLiked
		if err := rows.Scan(&i.UserID, &i.ItemID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByUserID = `-- name: GetByUserID :many
SELECT
  user_id, item_id, created_at
FROM
  "user"."liked"
WHERE
  user_id = $1
`

func (q *Queries) GetByUserID(ctx context.Context, userID string) ([]UserLiked, error) {
	rows, err := q.db.Query(ctx, getByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserLiked{}
	for rows.Next() {
		var i UserLiked
		if err := rows.Scan(&i.UserID, &i.ItemID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const like = `-- name: Like :exec
INSERT INTO
"user"."liked" (user_id, item_id)
VALUES
($1, $2)
RETURNING user_id, item_id, created_at
`

type LikeParams struct {
	UserID string `json:"user_id"`
	ItemID int64  `json:"item_id"`
}

func (q *Queries) Like(ctx context.Context, arg LikeParams) error {
	_, err := q.db.Exec(ctx, like, arg.UserID, arg.ItemID)
	return err
}

const unlike = `-- name: Unlike :exec
DELETE FROM
"user"."liked"
WHERE
user_id = $1 AND item_id = $2
RETURNING user_id, item_id, created_at
`

type UnlikeParams struct {
	UserID string `json:"user_id"`
	ItemID int64  `json:"item_id"`
}

func (q *Queries) Unlike(ctx context.Context, arg UnlikeParams) error {
	_, err := q.db.Exec(ctx, unlike, arg.UserID, arg.ItemID)
	return err
}
