// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package userviewed

import (
	"context"
)

const create = `-- name: Create :exec
INSERT INTO
"user"."viewed" (user_id, item_id)
VALUES
($1, $2)
RETURNING user_id, item_id, created_at
`

type CreateParams struct {
	UserID string `json:"user_id"`
	ItemID int64  `json:"item_id"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) error {
	_, err := q.db.Exec(ctx, create, arg.UserID, arg.ItemID)
	return err
}

const getViewed = `-- name: GetViewed :many
SELECT
item_id
FROM "user"."viewed"
WHERE user_id = $1
`

func (q *Queries) GetViewed(ctx context.Context, userID string) ([]int64, error) {
	rows, err := q.db.Query(ctx, getViewed, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var item_id int64
		if err := rows.Scan(&item_id); err != nil {
			return nil, err
		}
		items = append(items, item_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
