// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package userviewed

import (
	"context"
)

const create = `-- name: Create :exec
INSERT INTO
"user"."viewed" (user_id, item_id)
VALUES
($1, $2)
RETURNING user_id, item_id, created_at
`

type CreateParams struct {
	UserID string `json:"user_id"`
	ItemID int64  `json:"item_id"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) error {
	_, err := q.db.Exec(ctx, create, arg.UserID, arg.ItemID)
	return err
}
