basePath: /
definitions:
  item.CreateParams:
    properties:
      category:
        type: string
      condition:
        type: integer
      description:
        type: string
      images:
        items:
          type: string
        type: array
      is_negotiable:
        type: boolean
      name:
        type: string
      price:
        type: number
      sub_category:
        type: string
    type: object
  item.Item:
    properties:
      category:
        type: string
      condition:
        type: integer
      description:
        type: string
      fts: {}
      id:
        type: integer
      images:
        items:
          type: string
        type: array
      is_negotiable:
        type: boolean
      name:
        type: string
      posted_at:
        type: string
      price:
        type: number
      sold_at:
        $ref: '#/definitions/pgtype.Timestamptz'
      sub_category:
        type: string
      views:
        type: integer
    type: object
  item.UpdateParams:
    properties:
      condition:
        type: integer
      description:
        type: string
      id:
        type: integer
      images:
        items:
          type: string
        type: array
      is_negotiable:
        type: boolean
      name:
        type: string
      price:
        type: number
      views:
        type: integer
    type: object
  pgtype.InfinityModifier:
    enum:
    - 1
    - 0
    - -1
    format: int32
    type: integer
    x-enum-varnames:
    - Infinity
    - Finite
    - NegativeInfinity
  pgtype.Timestamptz:
    properties:
      infinityModifier:
        $ref: '#/definitions/pgtype.InfinityModifier'
      time:
        type: string
      valid:
        type: boolean
    type: object
  storage.PresignParams:
    properties:
      bucket:
        type: string
      contentType:
        type: string
      key:
        type: string
      method:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is the REST API for DooleyOnline.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: DooleyOnline API
  version: "1.0"
paths:
  /:
    get:
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Greeting
  /item:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/item.Item'
            type: array
      summary: Get all items
      tags:
      - item
    post:
      consumes:
      - application/json
      parameters:
      - description: Item
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/item.CreateParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/item.Item'
      summary: Create item
      tags:
      - item
  /item/{id}:
    delete:
      parameters:
      - description: Item ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: Item ID
          schema:
            type: string
      summary: Delete item by ID
      tags:
      - item
    get:
      parameters:
      - description: Item ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/item.Item'
      summary: Get item by ID
      tags:
      - item
    put:
      consumes:
      - application/json
      parameters:
      - description: Item ID
        in: path
        name: id
        required: true
        type: integer
      - description: Item
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/item.UpdateParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/item.Item'
      summary: Update item by ID
      tags:
      - item
  /item/{id}/sell:
    post:
      parameters:
      - description: Item ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: Item ID
          schema:
            type: string
      summary: Update sold_at property by ID
      tags:
      - item
  /item/{id}/view:
    post:
      parameters:
      - description: Item ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: Item ID
          schema:
            type: string
      summary: Increment item views by ID
      tags:
      - item
  /item/search:
    get:
      parameters:
      - description: Search query
        in: query
        name: query
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/item.Item'
            type: array
      summary: Search items by query
      tags:
      - item
  /storage/presign:
    post:
      consumes:
      - application/json
      parameters:
      - description: Presign params
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/storage.PresignParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/item.Item'
      summary: Generate presigned URL for s3 operation
      tags:
      - other
swagger: "2.0"
