// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sql

import (
	"time"
)

type Item struct {
	ID           int64
	Name         string
	Description  string
	Images       []string
	Price        float64
	Condition    int16
	IsNegotiable bool
	PostedAt     time.Time
	SoldAt       **time.Time
	Views        int64
}
