// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sql

import (
	"context"

	"time"
)

const createItem = `-- name: CreateItem :one
INSERT INTO
  item (name, description, images, price, condition, is_negotiable)
VALUES
  ($1, $2, $3, $4, $5, $6)
RETURNING id, name, description, images, price, condition, is_negotiable, posted_at, sold_at, views
`

type CreateItemParams struct {
	Name         string
	Description  string
	Images       []string
	Price        float64
	Condition    int16
	IsNegotiable bool
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.Name,
		arg.Description,
		arg.Images,
		arg.Price,
		arg.Condition,
		arg.IsNegotiable,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Images,
		&i.Price,
		&i.Condition,
		&i.IsNegotiable,
		&i.PostedAt,
		&i.SoldAt,
		&i.Views,
	)
	return i, err
}

const deleteItem = `-- name: DeleteItem :exec
DELETE FROM
  item
WHERE
  id = $1
`

func (q *Queries) DeleteItem(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteItem, id)
	return err
}

const getAllItems = `-- name: GetAllItems :many
SELECT
 id, name, description, images, price, condition, is_negotiable, posted_at, sold_at, views
FROM
 item
`

func (q *Queries) GetAllItems(ctx context.Context) ([]Item, error) {
	rows, err := q.db.Query(ctx, getAllItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Images,
			&i.Price,
			&i.Condition,
			&i.IsNegotiable,
			&i.PostedAt,
			&i.SoldAt,
			&i.Views,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItem = `-- name: GetItem :one
SELECT
  id, name, description, images, price, condition, is_negotiable, posted_at, sold_at, views
FROM
  item
WHERE
  id = $1
`

func (q *Queries) GetItem(ctx context.Context, id int64) (Item, error) {
	row := q.db.QueryRow(ctx, getItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Images,
		&i.Price,
		&i.Condition,
		&i.IsNegotiable,
		&i.PostedAt,
		&i.SoldAt,
		&i.Views,
	)
	return i, err
}

const incrementItemView = `-- name: IncrementItemView :exec
UPDATE
  item
SET
  views = views + 1
WHERE
  id = $1
`

func (q *Queries) IncrementItemView(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementItemView, id)
	return err
}

const updateItem = `-- name: UpdateItem :one
UPDATE
  item
SET
  name = $2,
  description = $3,
  images = $4,
  price = $5,
  condition = $6,
  is_negotiable = $7,
  sold_at = $8,
  views = $9
WHERE
  id = $1
RETURNING id, name, description, images, price, condition, is_negotiable, posted_at, sold_at, views
`

type UpdateItemParams struct {
	ID           int64
	Name         string
	Description  string
	Images       []string
	Price        float64
	Condition    int16
	IsNegotiable bool
	SoldAt       **time.Time
	Views        int64
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, updateItem,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Images,
		arg.Price,
		arg.Condition,
		arg.IsNegotiable,
		arg.SoldAt,
		arg.Views,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Images,
		&i.Price,
		&i.Condition,
		&i.IsNegotiable,
		&i.PostedAt,
		&i.SoldAt,
		&i.Views,
	)
	return i, err
}
